<a href="https://colab.research.google.com/github/Sejalm18/MBA-Projects/blob/main/AdviseInvestLogistic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Logistic Regression Example:  AdviseInvest

# Import necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split


from statsmodels.formula.api import logit
import statsmodels.api as sm

In [ ]:
#Upload AdviseInvestData.csv
from google.colab import files
uploaded = files.upload()

Saving AdviseInvestData.csv to AdviseInvestData (2).csv

In [ ]:
# read data
df = pd.read_csv("AdviseInvestData.csv")
#see the first few rows
df.head()

,OBS.,ANSWERED,INCOME,FEMALE,AGE,JOB,NUM_DEPENDENTS,RENT,OWN_RES,NEW_CAR,CHK_ACCT,SAV_ACCT,NUM_ACCTS,MOBILE,PRODUCT
0,133,1,13520,0,23,0,1,1,0,0,0,2,0,1,2
1,1509,0,14780,0,22,2,1,0,1,0,3,0,3,0,0
2,1530,1,37570,0,62,2,1,0,0,1,3,0,4,0,4
3,1886,0,12450,0,33,2,1,0,1,0,1,0,2,0,0
4,2463,0,12400,0,48,1,2,0,0,1,2,1,4,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29504 entries, 0 to 29503
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBS.            29504 non-null  int64
 1   ANSWERED        29504 non-null  int64
 2   INCOME          29504 non-null  int64
 3   FEMALE          29504 non-null  int64
 4   AGE             29504 non-null  int64
 5   JOB             29504 non-null  int64
 6   NUM_DEPENDENTS  29504 non-null  int64
 7   RENT            29504 non-null  int64
 8   OWN_RES         29504 non-null  int64
 9   NEW_CAR         29504 non-null  int64
 10  CHK_ACCT        29504 non-null  int64
 11  SAV_ACCT        29504 non-null  int64
 12  NUM_ACCTS       29504 non-null  int64
 13  MOBILE          29504 non-null  int64
 14  PRODUCT         29504 non-null  int64
dtypes: int64(15)
memory usage: 3.4 MB

In [ ]:
# Convert relevant columns to categorical types
categorical_columns = ['FEMALE', 'JOB', 'RENT', 'OWN_RES', 'NEW_CAR','CHK_ACCT','SAV_ACCT','MOBILE','PRODUCT']
df[categorical_columns] = df[categorical_columns].astype('category')

In [ ]:
#see that it worked
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29504 entries, 0 to 29503
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OBS.            29504 non-null  int64
 1   ANSWERED        29504 non-null  int64
 2   INCOME          29504 non-null  int64
 3   FEMALE          29504 non-null  category
 4   AGE             29504 non-null  int64
 5   JOB             29504 non-null  category
 6   NUM_DEPENDENTS  29504 non-null  int64
 7   RENT            29504 non-null  category
 8   OWN_RES         29504 non-null  category
 9   NEW_CAR         29504 non-null  category
 10  CHK_ACCT        29504 non-null  category
 11  SAV_ACCT        29504 non-null  category
 12  NUM_ACCTS       29504 non-null  int64
 13  MOBILE          29504 non-null  category
 14  PRODUCT         29504 non-null  category
dtypes: category(9), int64(6)
memory usage: 1.6 MB

In [ ]:
df.describe(include='all')

In [ ]:
answered_percentage = df['ANSWERED'].mean() * 100
print(f"Percentage of customers who answered the sales call: {answered_percentage:.2f}%")

Percentage of customers who answered the sales call: 54.66%

What is the percentage of the customers who answer the sales call?

In [ ]:
# Split into training (80%) and testing (20%) sets
#The random_state parameter can be set to any integer value. The choice of the value itself does not matter; what matters is that it is fixed.

train_df, test_df = train_test_split(df, test_size=0.2, random_state=1)
train_df.head()

,OBS.,ANSWERED,INCOME,FEMALE,AGE,JOB,NUM_DEPENDENTS,RENT,OWN_RES,NEW_CAR,CHK_ACCT,SAV_ACCT,NUM_ACCTS,MOBILE,PRODUCT
11864,4008424,0,80860,0,42,3,1,0,1,1,1,1,4,0,0
27205,9206967,1,19130,0,36,2,1,0,1,0,1,3,1,0,3
8994,3019072,1,51170,0,26,2,1,0,1,0,3,0,3,0,4
18258,6194642,1,13600,0,31,2,1,0,1,0,3,0,2,0,2
28899,9782313,1,2760,0,22,1,1,1,0,1,1,0,2,0,4

In [ ]:
test_df.head()

,OBS.,ANSWERED,INCOME,FEMALE,AGE,JOB,NUM_DEPENDENTS,RENT,OWN_RES,NEW_CAR,CHK_ACCT,SAV_ACCT,NUM_ACCTS,MOBILE,PRODUCT
24580,8328389,1,28720,0,36,2,2,0,1,0,3,1,4,0,4
11015,3712699,1,18810,0,44,1,1,1,0,0,2,0,2,0,2
7477,2525009,0,12850,0,32,2,1,1,0,1,0,4,3,0,0
26268,8901360,0,12170,0,47,1,1,0,1,0,0,0,2,0,0
28727,9724715,0,102970,0,39,2,2,0,0,0,0,0,3,1,0

In [ ]:
# Split into training (80%) and testing (20%) sets
#The random_state parameter can be set to any integer value. The choice of the value itself does not matter; what matters is that it is fixed.

train_df, test_df = train_test_split(df, test_size=0.2, random_state=1)
train_df.head()

,OBS.,ANSWERED,INCOME,FEMALE,AGE,JOB,NUM_DEPENDENTS,RENT,OWN_RES,NEW_CAR,CHK_ACCT,SAV_ACCT,NUM_ACCTS,MOBILE,PRODUCT
11864,4008424,0,80860,0,42,3,1,0,1,1,1,1,4,0,0
27205,9206967,1,19130,0,36,2,1,0,1,0,1,3,1,0,3
8994,3019072,1,51170,0,26,2,1,0,1,0,3,0,3,0,4
18258,6194642,1,13600,0,31,2,1,0,1,0,3,0,2,0,2
28899,9782313,1,2760,0,22,1,1,1,0,1,1,0,2,0,4

In [ ]:
test_df.head()

,OBS.,ANSWERED,INCOME,FEMALE,AGE,JOB,NUM_DEPENDENTS,RENT,OWN_RES,NEW_CAR,CHK_ACCT,SAV_ACCT,NUM_ACCTS,MOBILE,PRODUCT
24580,8328389,1,28720,0,36,2,2,0,1,0,3,1,4,0,4
11015,3712699,1,18810,0,44,1,1,1,0,0,2,0,2,0,2
7477,2525009,0,12850,0,32,2,1,1,0,1,0,4,3,0,0
26268,8901360,0,12170,0,47,1,1,0,1,0,0,0,2,0,0
28727,9724715,0,102970,0,39,2,2,0,0,0,0,0,3,1,0

Fit a simple logistic regression model with INCOME only.

In [ ]:
#Fit a logistic regression model with INCOME only.
#Is INCOME a significant predictor of who will answer the sales call?
#What is the Pseudo R2 of this model?

In [ ]:
model1 = logit("ANSWERED ~ INCOME", data=train_df).fit()
print(model1.summary())

Optimization terminated successfully.
         Current function value: 0.662552
         Iterations 5
                           Logit Regression Results
==============================================================================
Dep. Variable:               ANSWERED   No. Observations:                23603
Model:                          Logit   Df Residuals:                    23601
Method:                           MLE   Df Model:                            1
Date:                Wed, 08 Apr 2026   Pseudo R-squ.:                 0.03807
Time:                        18:19:56   Log-Likelihood:                -15638.
converged:                       True   LL-Null:                       -16257.
Covariance Type:            nonrobust   LLR p-value:                3.390e-271
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.7415      0.021     35.163      0.000       0.700       0.783
INCOME     -1.655e-05   5.01e-07    -33.038      0.000   -1.75e-05   -1.56e-05
==============================================================================

In [ ]:
#to predict one observation
# Create a DataFrame with the new observations
#only income is needed, other predictors are not be used by the model
new_data = pd.DataFrame({"INCOME": [12000]})

# Predict the probability of default

In [ ]:
predicted_prob_one_obs = model1.predict(new_data)
print(f"Predicted probability for INCOME=12000: {predicted_prob_one_obs[0]:.4f}")

Predicted probability for INCOME=12000: 0.6325

In [ ]:
predicted_prob_one_obs = model1.predict(new_data)
print(f"Predicted probability for INCOME=12000: {predicted_prob_one_obs[0]:.4f}")

Predicted probability for INCOME=12000: 0.6325

In [ ]:
#predict all observations in the test set, store them in "predicted_prob1"

In [ ]:
test_df['predicted_prob1'] = model1.predict(test_df)
display(test_df[['INCOME', 'ANSWERED', 'predicted_prob1']].head())

       INCOME  ANSWERED  predicted_prob1
24580   28720         1         0.566181
11015   18810         1         0.605937
7477    12850         0         0.629223
26268   12170         0         0.631845
28727  102970         0         0.276411

In [ ]:
#Use a threshold of 0.5 to classify these predictions into 1 and 0 categories.
#1 corresponds to Predicted: Answer, 0 corresponds to Predicted:No answer
test_df['predicted_response_m1']=test_df['predicted_prob1'].apply(lambda x: 1 if x >= 0.5 else 0)

In [ ]:
#Use a threshold of 0.5 to classify these predictions into 1 and 0 categories.
#1 corresponds to Predicted: Answer, 0 corresponds to Predicted:No answer
test_df['predicted_response_m1']=test_df['predicted_prob1'].apply(lambda x: 1 if x >= 0.5 else 0)

In [ ]:
# Build confusion matrix using sklearn
# confusion_matrix(actual, predicted) returns a 2x2 matrix:
#
#                  Predicted: No Answer   Predicted: Answer
#  Actual: No answer       TN                    FP
#  Actual: Answered        FN                    TP
#
# TN (True Negatives):  correctly predicted no answer
# FP (False Positives): predicted answer, but customer did not ← costly for AdviseInvest
# FN (False Negatives): predicted no answer, but customer answered  ← forgone revenues
# TP (True Positives):  correctly predicted answer

from sklearn.metrics import confusion_matrix
test_confusionmatrix1 = confusion_matrix(test_df['ANSWERED'], test_df['predicted_response_m1'])
print('Confusion matrix for the testing set:')
print(test_confusionmatrix1)

Confusion matrix for the testing set:
[[ 847 1830]
 [ 505 2719]]

We will now calculate different measures of model fit using the confusion matrix. *Accuracy* is the proportion of correct predictions:
$$\textit{Accuracy}=\frac{TN+TP}{\text{no of observations}}$$

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_m1 = accuracy_score(test_df['ANSWERED'], test_df['predicted_response_m1'])
print(f"Accuracy for Model 1 (test set): {accuracy_m1:.3f}")

Accuracy for Model 1 (test set): 0.604

In [ ]:
# calculating accuracy automatically
from sklearn.metrics import accuracy_score

*Precision* is the percentage of time we make a correct "Answered" prediction out of all the times we make that prediction.

$Precision=\frac{TP}{TP+FP}$

In [ ]:
tn, fp, fn, tp = test_confusionmatrix1.ravel()
precision_m1 = tp / (tp + fp)
print(f"Precision for Model 1 (test set): {precision_m1:.3f}")

Precision for Model 1 (test set): 0.598

In [ ]:
from sklearn.metrics import precision_score

precision_m1_auto = precision_score(test_df['ANSWERED'], test_df['predicted_response_m1'])
print(f"Precision for Model 1 (test set, automatic): {precision_m1_auto:.3f}")

Precision for Model 1 (test set, automatic): 0.598

In [ ]:
#get AUC
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(test_df['ANSWERED'], test_df['predicted_prob1'])
print(f"AUC: {auc:.3f}")

AUC: 0.584

Now, let's include the other predictors in the data set in the logistic regression model. Should Product be included?

In [ ]:
formula = "ANSWERED ~ INCOME + FEMALE + AGE + JOB + NUM_DEPENDENTS + RENT + OWN_RES + NEW_CAR + CHK_ACCT + SAV_ACCT + NUM_ACCTS + MOBILE + PRODUCT"
model_all_vars = logit(formula, data=train_df).fit()
print(model_all_vars.summary())

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.000001
         Iterations: 35
                           Logit Regression Results
==============================================================================
Dep. Variable:               ANSWERED   No. Observations:                23603
Model:                          Logit   Df Residuals:                    23579
Method:                           MLE   Df Model:                           23
Date:                Wed, 08 Apr 2026   Pseudo R-squ.:                   1.000
Time:                        18:33:10   Log-Likelihood:              -0.012996
converged:                      False   LL-Null:                       -16257.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        -22.8266    419.603     -0.054      0.957    -845.233     799.580
FEMALE[T.1]       -3.8249     82.233     -0.047      0.963    -164.999     157.349
JOB[T.1]           6.6914    202.729      0.033      0.974    -390.651     404.034
JOB[T.2]           2.1850    105.963      0.021      0.984    -205.499     209.869
JOB[T.3]           5.7358    175.231      0.033      0.974    -337.711     349.183
RENT[T.1]         -4.1615    166.318     -0.025      0.980    -330.138     321.815
OWN_RES[T.1]      -3.4691    131.554     -0.026      0.979    -261.311     254.373
NEW_CAR[T.1]      -3.7546     64.434     -0.058      0.954    -130.042     122.533
CHK_ACCT[T.1]     -6.5226    494.937     -0.013      0.989    -976.581     963.536
CHK_ACCT[T.2]     -0.6597    321.448     -0.002      0.998    -630.685     629.366
CHK_ACCT[T.3]     -7.7246    496.817     -0.016      0.988    -981.468     966.019
SAV_ACCT[T.1]      6.3841    251.405      0.025      0.980    -486.361     499.129
SAV_ACCT[T.2]     -3.2844     77.156     -0.043      0.966    -154.507     147.938
SAV_ACCT[T.3]      6.1137    753.915      0.008      0.994   -1471.533    1483.760
SAV_ACCT[T.4]      6.2497    512.616      0.012      0.990    -998.460    1010.959
MOBILE[T.1]       -0.3243    229.060     -0.001      0.999    -449.274     448.625
PRODUCT[T.1]      66.6418    3.7e+05      0.000      1.000   -7.26e+05    7.26e+05
PRODUCT[T.2]      50.3319    581.444      0.087      0.931   -1089.278    1189.942
PRODUCT[T.3]      48.6111    594.416      0.082      0.935   -1116.423    1213.645
PRODUCT[T.4]      53.5320    625.533      0.086      0.932   -1172.490    1279.554
INCOME          -5.93e-05      0.001     -0.043      0.966      -0.003       0.003
AGE               -0.0981      4.024     -0.024      0.981      -7.985       7.789
NUM_DEPENDENTS     2.2504    230.516      0.010      0.992    -449.552     454.053
NUM_ACCTS          0.2556     26.004      0.010      0.992     -50.710      51.222
==================================================================================

Possibly complete quasi-separation: A fraction 1.00 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.

/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "



```
# This is formatted as code
```

Drop the variables that are not significant and rerun the model.

In [ ]:
formula_without_product = "ANSWERED ~ INCOME + FEMALE + AGE + JOB + NUM_DEPENDENTS + RENT + OWN_RES + NEW_CAR + CHK_ACCT + SAV_ACCT + NUM_ACCTS + MOBILE"
model_without_product = logit(formula_without_product, data=train_df).fit()
print(model_without_product.summary())

Optimization terminated successfully.
         Current function value: 0.551527
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               ANSWERED   No. Observations:                23603
Model:                          Logit   Df Residuals:                    23583
Method:                           MLE   Df Model:                           19
Date:                Wed, 08 Apr 2026   Pseudo R-squ.:                  0.1993
Time:                        18:33:50   Log-Likelihood:                -13018.
converged:                       True   LL-Null:                       -16257.
Covariance Type:            nonrobust   LLR p-value:                     0.000
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -0.5677      0.141     -4.025      0.000      -0.844      -0.291
FEMALE[T.1]       -0.6137      0.069     -8.919      0.000      -0.749      -0.479
JOB[T.1]          -0.1761      0.101     -1.736      0.083      -0.375       0.023
JOB[T.2]          -0.2351      0.098     -2.387      0.017      -0.428      -0.042
JOB[T.3]          -0.4878      0.106     -4.601      0.000      -0.696      -0.280
RENT[T.1]          0.0524      0.065      0.812      0.417      -0.074       0.179
OWN_RES[T.1]       0.3773      0.057      6.634      0.000       0.266       0.489
NEW_CAR[T.1]      -0.5304      0.037    -14.520      0.000      -0.602      -0.459
CHK_ACCT[T.1]      0.2012      0.039      5.125      0.000       0.124       0.278
CHK_ACCT[T.2]      0.3498      0.063      5.543      0.000       0.226       0.474
CHK_ACCT[T.3]      1.6766      0.041     41.139      0.000       1.597       1.757
SAV_ACCT[T.1]     -0.0155      0.051     -0.302      0.762      -0.116       0.085
SAV_ACCT[T.2]      0.6825      0.069      9.901      0.000       0.547       0.818
SAV_ACCT[T.3]      1.2754      0.086     14.887      0.000       1.108       1.443
SAV_ACCT[T.4]      0.4615      0.047      9.849      0.000       0.370       0.553
MOBILE[T.1]        1.6169      0.068     23.773      0.000       1.484       1.750
INCOME         -2.102e-05   6.53e-07    -32.210      0.000   -2.23e-05   -1.97e-05
AGE                0.0145      0.002      9.147      0.000       0.011       0.018
NUM_DEPENDENTS    -0.1820      0.046     -3.964      0.000      -0.272      -0.092
NUM_ACCTS          0.1773      0.015     12.158      0.000       0.149       0.206
==================================================================================

In [ ]:
test_df['predicted_prob2'] = model_without_product.predict(test_df[formula_without_product.split('~')[1].strip().split(' + ')])

display(test_df[['INCOME', 'ANSWERED', 'predicted_prob2']].head())

       INCOME  ANSWERED  predicted_prob2
24580   28720         1         0.817660
11015   18810         1         0.518859
7477    12850         0         0.431889
26268   12170         0         0.558175
28727  102970         0         0.350811

In [ ]:
# Use a threshold of 0.09 to classify these predictions into 1 and 0 categories.
# 1 corresponds to Predicted: Answer, 0 corresponds to Predicted: No answer
test_df['predicted_response_m2'] = test_df['predicted_prob2'].apply(lambda x: 1 if x > 0.09 else 0)

# Build confusion matrix using sklearn
from sklearn.metrics import confusion_matrix
test_confusionmatrix2 = confusion_matrix(test_df['ANSWERED'], test_df['predicted_response_m2'])
print('Confusion matrix for Model 2 (test set) with threshold 0.09:')
print(test_confusionmatrix2)

Confusion matrix for Model 2 (test set) with threshold 0.09:
[[ 131 2546]
 [  15 3209]]

Calculate the accuracy, precision and AUC for this model.

In [ ]:
accuracy_m2 = accuracy_score(test_df['ANSWERED'], test_df['predicted_response_m2'])
print(f"Accuracy for Model 2 (test set): {accuracy_m2:.3f}")

Accuracy for Model 2 (test set): 0.566

In [ ]:
precision_m2 = precision_score(test_df['ANSWERED'], test_df['predicted_response_m2'])
print(f"Precision for Model 2 (test set): {precision_m2:.3f}")

Precision for Model 2 (test set): 0.558

In [ ]:
#get AUC
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(test_df['ANSWERED'], test_df['predicted_prob2'])
print(f"AUC: {auc:.3f}")

AUC: 0.790

We will now do k-fold cross validation. Instead of splitting the data into training/testing only once randomly, we will do it 5 times and look at the average accuracy. This way, we reduce the effect of being unlucky or lucky with the single training/testing split.

In [ ]:
#k-fold cross validation
from sklearn.linear_model import LogisticRegression #easier to use logistic regression from scikit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [ ]:
#model 2:
X = df[['INCOME', 'FEMALE', 'AGE', 'JOB','NUM_DEPENDENTS' ,'OWN_RES', 'NEW_CAR', 'CHK_ACCT', 'SAV_ACCT' ,'NUM_ACCTS','MOBILE']]
y = df['ANSWERED']



# Logistic Regression model
model = LogisticRegression(max_iter=5000)

# Define 5-fold cross-validation
cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Run cross-validation and get precision scores
scores_acc = cross_val_score(model, X, y, cv=cv, scoring='accuracy')
scores_prec = cross_val_score(model, X, y, cv=cv, scoring='precision')

# Output the results
print(f"Cross-Validation Accuracy Scores: {scores_acc}")
print(f"Mean Accuracy: {np.mean(scores_acc):.3f}")
print(f"Standard Deviation: {np.std(scores_acc):.3f}")
print()
print(f"Cross-Validation Precision Scores: {scores_prec}")
print(f"Mean Precision: {np.mean(scores_prec):.3f}")
print(f"Standard Deviation: {np.std(scores_prec):.3f}")

Cross-Validation Accuracy Scores: [0.71225216 0.70852398 0.72106423 0.72360617 0.69966102]
Mean Accuracy: 0.713
Standard Deviation: 0.009

Cross-Validation Precision Scores: [0.72191697 0.72534785 0.73716012 0.74811463 0.72688822]
Mean Precision: 0.732
Standard Deviation: 0.010